### ISSUE TITLE
NaN% displays when indicator calculation status is queued

### ISSUE THREAD

**Issue by jfrankl** [WorldBank-Transport/open-transit-indicators#607]
When a Indicator calculation status is queued, the value on the progress bar displays NaN% until the first indicator is calculated, at which point it displays the correct percentage. Can we change this to show "0%" instead of "NaN%"?

![image](https://cloud.githubusercontent.com/assets/1809908/5616961/6f48b446-94d7-11e4-89d7-e85ef7650025.png)

**Comment by jfrankl** [comment]
Not sure if you're the right person for this Nathan, but I believe you were working on this page at some point.

**Comment by ddohler** [comment]
I'll include a fix for this in the map layer updates I'm working on.
