### ISSUE TITLE
Bower Error in Production Setup on Ubuntu 12.04

### ISSUE THREAD

**Issue by radumas** [WorldBank-Transport/open-transit-indicators#625]
I am setting this up on a Digital Oceans server running Ubuntu Server 12.04 and I get the following error when running `sudo ./deployment/provision.sh production` when everything, more or less, up to that point has been smooth. 

>Setting up celery upstart services
stop: Unknown instance: 
oti-celery-datasources start/running, process 9155
oti-celery-indicators stop/waiting
oti-celery-indicators start/running, process 9174
oti-celery-scenarios stop/waiting
oti-celery-scenarios start/running, process 9191
Finished setting up celery and background processes started
Setting up angular
/home/oti/open-transit-indicators/js/angular /home/oti/open-transit-indicators
bower leaflet-utfgrid#*     not-cached git://github.com/danzel/Leaflet.utfgrid.git#*
bower leaflet-utfgrid#*        resolve git://github.com/danzel/Leaflet.utfgrid.git#*
bower leaflet-tilelayer-geojson#*       not-cached git://github.com/glenrobertson/leaflet-tilelayer-geojson.git#*
bower leaflet-tilelayer-geojson#*          resolve git://github.com/glenrobertson/leaflet-tilelayer-geojson.git#*
bower leaflet-label#*                       cached git://github.com/Leaflet/Leaflet.label.git#0.2.1
bower leaflet-label#*                     validate 0.2.1 against git://github.com/Leaflet/Leaflet.label.git#*
bower angular#1.3.1                         cached git://github.com/angular/bower-angular.git#1.3.1
bower angular#1.3.1                       validate 1.3.1 against git://github.com/angular/bower-angular.git#1.3.1
bower json3#~3.2.6                          cached git://github.com/bestiejs/json3.git#3.2.6
bower json3#~3.2.6                        validate 3.2.6 against git://github.com/bestiejs/json3.git#~3.2.6
bower es5-shim#~2.1.0                       cached git://github.com/es-shims/es5-shim.git#2.1.0
bower es5-shim#~2.1.0                     validate 2.1.0 against git://github.com/es-shims/es5-shim.git#~2.1.0
bower jquery#~1.11.0                        cached git://github.com/jquery/jquery.git#1.11.2
bower jquery#~1.11.0                      validate 1.11.2 against git://github.com/jquery/jquery.git#~1.11.0
bower angular-animate#1.3.1                 cached git://github.com/angular/bower-angular-animate.git#1.3.1
bower angular-animate#1.3.1               validate 1.3.1 against git://github.com/angular/bower-angular-animate.git#1.3.1
bower angular-resource#1.3.1                cached git://github.com/angular/bower-angular-resource.git#1.3.1
bower angular-resource#1.3.1              validate 1.3.1 against git://github.com/angular/bower-angular-resource.git#1.3.1
bower angular-cookies#1.3.1                 cached git://github.com/angular/bower-angular-cookies.git#1.3.1
bower angular-cookies#1.3.1               validate 1.3.1 against git://github.com/angular/bower-angular-cookies.git#1.3.1
bower ng-file-upload#1.3.1                  cached git://github.com/danialfarid/angular-file-upload-bower.git#1.3.1
bower ng-file-upload#1.3.1                validate 1.3.1 against git://github.com/danialfarid/angular-file-upload-bower.git#1.3.1
bower angular-ui-router#0.2.10              cached git://github.com/angular-ui/ui-router.git#0.2.10
bower angular-ui-router#0.2.10            validate 0.2.10 against git://github.com/angular-ui/ui-router.git#0.2.10
bower angular-translate#2.2.0               cached git://github.com/PascalPrecht/bower-angular-translate.git#2.2.0
bower angular-translate#2.2.0             validate 2.2.0 against git://github.com/PascalPrecht/bower-angular-translate.git#2.2.0
bower angular-translate-loader-static-files#2.2.0           cached git://github.com/PascalPrecht/bower-angular-translate-loader-static-files.git#2.2.0
bower angular-translate-loader-static-files#2.2.0         validate 2.2.0 against git://github.com/PascalPrecht/bower-angular-translate-loader-static-files.git#2.2.0
bower angular-translate-handler-log#2.0.1                   cached git://github.com/PascalPrecht/bower-angular-translate-handler-log.git#2.0.1
bower angular-translate-handler-log#2.0.1                 validate 2.0.1 against git://github.com/PascalPrecht/bower-angular-translate-handler-log.git#2.0.1
bower angular-bootstrap#0.12.0                              cached git://github.com/angular-ui/bootstrap-bower.git#0.12.0
bower angular-bootstrap#0.12.0                            validate 0.12.0 against git://github.com/angular-ui/bootstrap-bower.git#0.12.0
bower angular-ui-utils#0.1.1                                cached git://github.com/angular-ui/ui-utils.git#0.1.1
bower angular-ui-utils#0.1.1                              validate 0.1.1 against git://github.com/angular-ui/ui-utils.git#0.1.1
bower underscore#1.6.0                                      cached git://github.com/jashkenas/underscore.git#1.6.0
bower underscore#1.6.0                                    validate 1.6.0 against git://github.com/jashkenas/underscore.git#1.6.0
bower bootstrap-sass-official#3.1.1+1                       cached git://github.com/twbs/bootstrap-sass.git#3.1.1+1
bower bootstrap-sass-official#3.1.1+1                     validate 3.1.1+1 against git://github.com/twbs/bootstrap-sass.git#3.1.1+1
bower leaflet#0.7.3                                         cached git://github.com/Leaflet/Leaflet.git#0.7.3
bower leaflet#0.7.3                                       validate 0.7.3 against git://github.com/Leaflet/Leaflet.git#0.7.3
bower leaflet.draw#~0.2.3                                   cached git://github.com/Leaflet/Leaflet.draw.git#0.2.3
bower leaflet.draw#~0.2.3                                 validate 0.2.3 against git://github.com/Leaflet/Leaflet.draw.git#~0.2.3
bower angularjs-nvd3-directives#~0.0.7                      cached git://github.com/cmaurer/angularjs-nvd3-directives.git#0.0.7
bower angularjs-nvd3-directives#~0.0.7                    validate 0.0.7 against git://github.com/cmaurer/angularjs-nvd3-directives.git#~0.0.7
bower angular-leaflet-directive#~0.7.9                      cached git://github.com/tombatossals/angular-leaflet-directive.git#0.7.11
bower angular-leaflet-directive#~0.7.9                    validate 0.7.11 against git://github.com/tombatossals/angular-leaflet-directive.git#~0.7.9
bower pace#~1.0.1                                           cached git://github.com/HubSpot/pace.git#1.0.2
bower pace#~1.0.1                                         validate 1.0.2 against git://github.com/HubSpot/pace.git#~1.0.1
bower angular-spinkit#~0.3.3                                cached git://github.com/Urigo/angular-spinkit.git#0.3.3
bower angular-spinkit#~0.3.3                              validate 0.3.3 against git://github.com/Urigo/angular-spinkit.git#~0.3.3
bower angular-mocks#1.3.1                                   cached git://github.com/angular/bower-angular-mocks.git#1.3.1
bower angular-mocks#1.3.1                                 validate 1.3.1 against git://github.com/angular/bower-angular-mocks.git#1.3.1
bower angular-scenario#1.3.1                                cached git://github.com/angular/bower-angular-scenario.git#1.3.1
bower angular-scenario#1.3.1                              validate 1.3.1 against git://github.com/angular/bower-angular-scenario.git#1.3.1
bower leaflet-tilelayer-geojson#*                         checkout master
bower leaflet-utfgrid#*                                   checkout master
bower angular#>=1 <1.3.0                                    cached git://github.com/angular/bower-angular.git#1.2.28
bower angular#>=1 <1.3.0                                  validate 1.2.28 against git://github.com/angular/bower-angular.git#>=1 <1.3.0
bower d3#~3.4.1                                             cached git://github.com/mbostock/d3.git#3.4.13
bower d3#~3.4.1                                           validate 3.4.13 against git://github.com/mbostock/d3.git#~3.4.1
bower nvd3#~v1.1.15-beta                                    cached git://github.com/novus/nvd3.git#1.1.15-beta
bower nvd3#~v1.1.15-beta                                  validate 1.1.15-beta against git://github.com/novus/nvd3.git#~v1.1.15-beta
bower font-awesome#~4.2.0                                   cached git://github.com/FortAwesome/Font-Awesome.git#4.2.0
bower font-awesome#~4.2.0                                 validate 4.2.0 against git://github.com/FortAwesome/Font-Awesome.git#~4.2.0
bower d3#~3.3.13                                            cached git://github.com/mbostock/d3.git#3.3.13
bower d3#~3.3.13                                          validate 3.3.13 against git://github.com/mbostock/d3.git#~3.3.13
bower leaflet-utfgrid#*                               invalid-meta leaflet-utfgrid is missing "main" entry in bower.json
bower leaflet-utfgrid#*                               invalid-meta leaflet-utfgrid is missing "ignore" entry in bower.json
bower leaflet-tilelayer-geojson#*                     invalid-meta leaflet-tilelayer-geojson is missing "main" entry in bower.json
bower leaflet-tilelayer-geojson#*                     invalid-meta leaflet-tilelayer-geojson is missing "ignore" entry in bower.json
bower leaflet-utfgrid#*                                   resolved git://github.com/danzel/Leaflet.utfgrid.git#0fe25764e8
bower leaflet-tilelayer-geojson#*                         resolved git://github.com/glenrobertson/leaflet-tilelayer-geojson.git#0bb95b7ce2

>Please note that,
    angular-bootstrap#0.12.0 depends on angular#>=1 <1.3.0 which resolved to angular#1.2.28
    angularjs-nvd3-directives#0.0.7 depends on angular#~1.2.4 which resolved to angular#1.2.28
    angular-animate#1.3.1, angular-cookies#1.3.1, angular-mocks#1.3.1, angular-resource#1.3.1, angular-scenario#1.3.1, transitIndicators depends on angular#1.3.1 which resolved to angular#1.3.1
    angular-ui-router#0.2.10 depends on angular#>= 1.0.8 which resolved to angular#1.3.1
    angular-ui-utils#0.1.1 depends on angular#>= 1.0.2 which resolved to angular#1.3.1
    angular-leaflet-directive#0.7.11 depends on angular#1.3.x which resolved to angular#1.3.1
    angular-spinkit#0.3.3 depends on angular#* which resolved to angular#1.3.1
Resort to using angular#1.3.1 which resolved to angular#1.3.1
Code incompatibilities may occur.

>Please note that,
    nvd3#1.1.15-beta depends on d3#~3.3.13 which resolved to d3#3.3.13
    angularjs-nvd3-directives#0.0.7 depends on d3#~3.4.1 which resolved to d3#3.4.13
Resort to using d3#~3.4.1 which resolved to d3#3.4.13
Code incompatibilities may occur.

>bower                                                       EACCES EACCES, mkdir '/home/oti/open-transit-indicators/js/angular/app/bower_components'

>Stack trace:
Error: EACCES, mkdir '/home/oti/open-transit-indicators/js/angular/app/bower_components'

>Console trace:
Trace
    at StandardRenderer.error (/usr/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:17)
    at Logger.<anonymous> (/usr/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/usr/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/lib/node_modules/bower/lib/commands/index.js:40:20
    at _rejected (/usr/lib/node_modules/bower/node_modules/q/q.js:797:24)
    at /usr/lib/node_modules/bower/node_modules/q/q.js:823:30
    at Promise.when (/usr/lib/node_modules/bower/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/bower/node_modules/q/q.js:741:41)
    at /usr/lib/node_modules/bower/node_modules/q/q.js:557:44

>System info:
Bower version: 1.3.12
Node version: 0.10.33
OS: Linux 3.13.0-32-generic x64`

**Comment by radumas** [comment]
Never mind! 

I initially created the folder as root.

**Comment by kshepard** [comment]
Glad you figured it out!
