### ISSUE TITLE
route_short_name max length 6 characters?

### ISSUE THREAD

**Issue by radumas** [WorldBank-Transport/open-transit-indicators#627]
Hello,

I uploaded data from the [MBTA](http://mbta.com/) which contains some `route_short_names` that caused the following error:

>Invalid value Shuttle in field route_short_name This route_short_name is relatively long, which probably means that it contains a place name. You should only use this field to hold a short code that riders use to identify a route. If this route doesn't have such a code, it's OK to leave this field empty.
Invalid value 441/442 in field route_short_name This route_short_name is relatively long, which probably means that it contains a place name. You should only use this field to hold a short code that riders use to identify a route. If this route doesn't have such a code, it's OK to leave this field empty.
Invalid value 214/216 in field route_short_name This route_short_name is relatively long, which probably means that it contains a place name. You should only use this field to hold a short code that riders use to identify a route. If this route doesn't have such a code, it's OK to leave this field empty.
Invalid value 116/117 in field route_short_name This route_short_name is relatively long, which probably means that it contains a place name. You should only use this field to hold a short code that riders use to identify a route. If this route doesn't have such a code, it's OK to leave this field empty.

Since it doesn't seem like this is likely to be a configuration that is too out of the ordinary for transit agencies to use, I am wondering if the `route_short_name` needs to be so short. The gtfs spec itself also doesn't specify a max length for this parameter.

As a tangential but related question: Does the uploader handle agencies adding extra fields beyond the gtfs spec?

Thanks,

-Raphael

**Comment by ddohler** [comment]
Hi Raphael,

We're using [transitfeed](https://github.com/google/transitfeed) to do feed validation, so the output you're seeing is coming from that library and we don't really have a way to control the warnings and errors it provides unless we fork it.

To answer your second question, I believe that the uploader will simply ignore extra fields that are outside the GTFS spec, but they shouldn't cause problems except a warning from the validator.

**Comment by radumas** [comment]
Bringing it up with them, thanks.
